// R7 Plan board: which agent works a task card, color-coded per agent (external subagents
// visible + colored parallel tracks). Pure + DOM-free. Generated by the local Qwen model.
import type { AgentClaim, AgentSession } from "../../types/backend";

export interface WorkerBadge {
  agentId: string;
  label: string;
  colorClass: string;
  external: boolean;
}

const PALETTE = [
  "bg-teal/15 text-teal",
  "bg-terracotta/15 text-terracotta",
  "bg-sage-dark/15 text-sage-dark",
  "bg-amber-dark/15 text-amber-dark",
  "bg-coral-dark/15 text-coral-dark",
  "bg-cream-500/15 text-cream-700",
] as const;

export function agentColorClass(agentId: string): string {
  let hash = 5381;
  for (let i = 0; i < agentId.length; i++) {
    hash = (hash << 5) + hash + agentId.charCodeAt(i);
  }
  const index = Math.abs(hash) % PALETTE.length;
  return PALETTE[index];
}

export function deriveWorkers(
  claims: AgentClaim[],
  sessions: AgentSession[],
): WorkerBadge[] {
  const seen = new Set<string>();
  const orderedIds: string[] = [];

  for (const claim of claims) {
    if (!seen.has(claim.agentId)) {
      seen.add(claim.agentId);
      orderedIds.push(claim.agentId);
    }
  }
  for (const session of sessions) {
    if (!seen.has(session.agentId)) {
      seen.add(session.agentId);
      orderedIds.push(session.agentId);
    }
  }

  const result: WorkerBadge[] = [];
  for (const agentId of orderedIds) {
    const session = sessions.find((s) => s.agentId === agentId);
    const claim = claims.find((c) => c.agentId === agentId);

    const role = session?.role ?? claim?.role ?? "agent";
    const labelValue = session?.client ?? session?.model ?? "agent";
    const label = `${role} · ${labelValue}`.trim();
    const external = session ? session.host !== "app" : true;

    result.push({
      agentId,
      label,
      colorClass: agentColorClass(agentId),
      external,
    });
  }
  return result;
}
