#!/usr/bin/env python3
"""Generate the typed TS sprite manifest from staged metas + packed atlases.

Cross-checks provenance (every staged ``source`` must be a known ledger entry,
every staged key must appear in exactly one atlas) and then emits
``src/components/polis/spriteManifest.ts`` atomically. The emitted file equals
the hand-authored placeholder except for (a) a generation note and (b) the
filled-in ``SPRITE_MANIFEST`` literal — so consumers get a stable API shape.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import tempfile
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
TEMPLATE_PATH = SCRIPT_DIR.parent.parent / "src" / "components" / "polis" / "spriteManifest.ts"

GEN_NOTE_OLD = (
    "Until A2 lands it is a hand-authored placeholder; keep the shapes in sync"
    "\n// with the generator."
)
GEN_NOTE_NEW = (
    "GENERATED by tools/polis-art/manifest.py — do NOT hand-edit; re-run the "
    "pipeline instead."
)
MANIFEST_BLOCK_RE = re.compile(
    r"export const SPRITE_MANIFEST: SpriteManifest = \{.*?\n\};", re.DOTALL
)
DEFAULT_ANCHOR = [0.5, 1.0]

_EMBEDDED_TEMPLATE = """\
// Polis sprite manifest — the typed index of every real-art sprite the renderer
// may use, keyed by SEMANTIC key, decoupled from atlas layout.
//
// KEY GRAMMAR (stable API for the whole sprite round; consumers never touch
// frame names):
//   bld:{purpose}:{level}:v{n}   whole-building sprite variant (A5b)
//   tex:{surface}                seamless fill texture (grass/cobble/plaster/...)
//   prop:{kind}:v{n}             scatter prop (olive/rock/stall/...)
//   field:{kind}                 farmland parcel texture per fields.ts kind
//   walk:{type}:{dir}:f{n}       walker animation frame (A6)
//   fx:{effect}:f{n}             flipbook effect frame (fire/smoke, A7)
//
// GENERATION: this file is emitted by tools/polis-art/manifest.py (phase A2)
// from docs/polis-art-ledger.json + the packed atlases in public/polis/atlas/.
// Until A2 lands it is a hand-authored placeholder; keep the shapes in sync
// with the generator. An EMPTY manifest is the shipped state of record until
// assets land — loadPolisSprites returns null and every draw path stays on the
// procedural kit.

/**
 * Per-sprite metadata carried alongside the atlas frame reference. Deliberately
 * deep-readonly: entries are shared by reference between the manifest and every
 * SpriteBank, so a writable field here would let one consumer silently corrupt
 * the anchor/footprint of every building using the same key.
 */
export interface SpriteEntryMeta {
  /** Frame name inside the owning atlas spritesheet. */
  readonly frame: string;
  /** Id of the atlas page (key into SpriteManifest.atlases) holding the frame. */
  readonly atlas: string;
  /** Building footprint in tiles [W, D] — building sprites only. */
  readonly foot?: readonly [number, number];
  /**
   * Anchor in normalized texture coords. Default [0.5, 1]: bottom-center, so a
   * sprite placed at the footprint's front-corner iso point sits on the ground
   * like the kit containers do.
   */
  readonly anchor?: readonly [number, number];
  /**
   * True when the source art bakes its own ground shadow — the renderer must
   * then skip our contact-shadow sprite for this variant or shadows double up.
   */
  readonly hasBakedShadow?: boolean;
}

export interface SpriteManifest {
  version: 1;
  /**
   * Atlas pages: page id -> spritesheet JSON url (app-root relative, served
   * from public/polis/atlas/, CSP 'self').
   */
  atlases: Record<string, string>;
  /** Semantic key -> frame metadata. */
  entries: Record<string, SpriteEntryMeta>;
}

/** Shipped manifest. Empty until phase A2/A3 land the first packed atlases. */
export const SPRITE_MANIFEST: SpriteManifest = {
  version: 1,
  atlases: {},
  entries: {},
};
"""


def load_template() -> str:
    """Prefer the live repo placeholder; fall back to an embedded copy if absent."""
    if TEMPLATE_PATH.exists():
        return TEMPLATE_PATH.read_text(encoding="utf-8")
    return _EMBEDDED_TEMPLATE


def fmt_num(x: float) -> str:
    """Render numbers the way the shipped TS does (1.0 -> '1', 0.5 -> '0.5')."""
    if isinstance(x, bool):
        return "true" if x else "false"
    f = float(x)
    if f.is_integer():
        return str(int(f))
    return repr(f)


def load_metas(staged: Path) -> list[dict]:
    metas: list[dict] = []
    if not staged.exists():
        return metas
    for group_dir in sorted(p for p in staged.iterdir() if p.is_dir()):
        for meta_path in sorted(group_dir.glob("*.meta.json")):
            metas.append(json.loads(meta_path.read_text(encoding="utf-8")))
    return metas


def load_atlases(atlas_dir: Path) -> tuple[dict[str, str], dict[str, set]]:
    """Return (page_id -> json filename) and (frame -> set of page ids)."""
    page_files: dict[str, str] = {}
    frame_pages: dict[str, set] = {}
    for aj in sorted(atlas_dir.glob("*.json")):
        page_id = aj.stem
        page_files[page_id] = aj.name
        data = json.loads(aj.read_text(encoding="utf-8"))
        for fname in data.get("frames", {}):
            frame_pages.setdefault(fname, set()).add(page_id)
    return page_files, frame_pages


def check_variant_families(metas: list[dict], warnings: list[str]) -> None:
    """Warn (non-fatal) when a ':vN' family is not contiguous from v0."""
    families: dict[str, list[int]] = {}
    for m in metas:
        parts = m["key"].split(":")
        if parts and re.fullmatch(r"v\d+", parts[-1]):
            fam = ":".join(parts[:-1])
            families.setdefault(fam, []).append(int(parts[-1][1:]))
    for fam, vers in families.items():
        vers.sort()
        expected = list(range(vers[0], vers[0] + len(vers)))
        if vers != expected or vers[0] != 0:
            warnings.append(
                f"variant family '{fam}' not contiguous from v0: {vers}"
            )


def validate(metas: list[dict], page_files: dict[str, str],
             frame_pages: dict[str, set], atlas_dir: Path,
             ledger_sources: dict) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []

    seen_keys: dict[str, int] = {}
    for m in metas:
        key = m["key"]
        seen_keys[key] = seen_keys.get(key, 0) + 1
        if m["source"] not in ledger_sources:
            errors.append(
                f"source '{m['source']}' for key '{key}' not listed in ledger"
            )

    for key, count in seen_keys.items():
        if count > 1:
            errors.append(f"duplicate staged key '{key}'")
        pages = frame_pages.get(key, set())
        if len(pages) == 0:
            errors.append(f"key '{key}' not found in any atlas")
        elif len(pages) > 1:
            errors.append(f"key '{key}' appears in multiple atlases: {sorted(pages)}")

    for page_id, fname in page_files.items():
        if not (atlas_dir / fname).exists():
            errors.append(f"atlas image '{fname}' (page '{page_id}') missing")

    check_variant_families(metas, warnings)
    return errors, warnings


def build_entries(metas: list[dict], frame_pages: dict[str, set]) -> dict[str, dict]:
    """Build entries sorted by key; omit default anchor, false baked, absent foot."""
    entries: dict[str, dict] = {}
    for m in metas:
        key = m["key"]
        pages = sorted(frame_pages.get(key, set()))
        page_id = pages[0] if pages else ""
        anchor = m.get("anchor", DEFAULT_ANCHOR)
        entry: dict[str, Any] = {"frame": key, "atlas": page_id}
        if m.get("foot") is not None:
            entry["foot"] = list(m["foot"])
        if anchor != DEFAULT_ANCHOR:
            entry["anchor"] = list(anchor)
        if m.get("hasBakedShadow"):
            entry["hasBakedShadow"] = True
        entries[key] = entry
    return entries


def render_block(atlases: dict[str, str], entries: dict[str, dict]) -> str:
    lines: list[str] = []
    lines.append("export const SPRITE_MANIFEST: SpriteManifest = {")
    lines.append("  version: 1,")
    if atlases:
        lines.append("  atlases: {")
        pids = sorted(atlases)
        for i, pid in enumerate(pids):
            comma = "," if i < len(pids) - 1 else ""
            lines.append(f'    "{pid}": "{atlases[pid]}"{comma}')
        lines.append("  },")
    else:
        lines.append("  atlases: {},")
    lines.append("  entries: {")
    keys = sorted(entries)
    for i, key in enumerate(keys):
        comma = "," if i < len(keys) - 1 else ""
        inner: list[str] = []
        e = entries[key]
        inner.append(f'frame: "{e["frame"]}"')
        inner.append(f'atlas: "{e["atlas"]}"')
        if "foot" in e:
            f = e["foot"]
            inner.append(f"foot: [{fmt_num(f[0])}, {fmt_num(f[1])}]")
        if "anchor" in e:
            a = e["anchor"]
            inner.append(f"anchor: [{fmt_num(a[0])}, {fmt_num(a[1])}]")
        if e.get("hasBakedShadow"):
            inner.append("hasBakedShadow: true")
        lines.append(f'    "{key}": {{')
        for j, prop in enumerate(inner):
            c = "," if j < len(inner) - 1 else ""
            lines.append(f"      {prop}{c}")
        lines.append(f"    }}{comma}")
    lines.append("  }")
    lines.append("};")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate spriteManifest.ts")
    parser.add_argument("--staged", required=True, type=Path)
    parser.add_argument("--atlas-dir", required=True, type=Path)
    parser.add_argument("--ledger", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument("--atlas-url-prefix", default="/polis/atlas/")
    args = parser.parse_args(argv)

    metas = load_metas(args.staged)
    page_files, frame_pages = load_atlases(args.atlas_dir)
    ledger = json.loads(args.ledger.read_text(encoding="utf-8"))
    ledger_sources = ledger.get("sources", {})

    errors, warnings = validate(metas, page_files, frame_pages, args.atlas_dir,
                                ledger_sources)
    for w in warnings:
        print(f"WARNING {w}", file=sys.stderr)
    if errors:
        for e in errors:
            print(f"ERROR {e}", file=sys.stderr)
        return 1

    atlases = {pid: args.atlas_url_prefix + fname for pid, fname in page_files.items()}
    entries = build_entries(metas, frame_pages)
    block = render_block(atlases, entries)

    template = load_template().replace(GEN_NOTE_OLD, GEN_NOTE_NEW)
    template = MANIFEST_BLOCK_RE.sub(lambda _m: block, template, count=1)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=str(args.out.parent), suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(template)
        os.replace(tmp, args.out)
    finally:
        try:
            os.remove(tmp)
        except OSError:
            pass
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
