// S4 — "recommended for your machine": surfaces the backend's recommend_resource_config
// (detect_hardware → per-role model recommendation + rationale), which existed but was never
// shown in the UI. Display-only (no auto-apply). Generated by the local Qwen model.
import { useEffect, useState, useCallback } from "react";
import { invokeBackendCommand } from "../../context/AppContext";

interface RecommendedConfig {
  tier: string;
  mainCoder: string;
  miniCoder: string;
  censor: string;
  oracle: string;
  rationale: string;
}

export function RecommendedConfigCard() {
  const [config, setConfig] = useState<RecommendedConfig | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(() => {
    setLoading(true);
    invokeBackendCommand<RecommendedConfig>("recommend_resource_config")
      .then((data) => {
        setConfig(data);
        setLoading(false);
      })
      .catch((message) => {
        setError(message instanceof Error ? message.message : String(message));
        setLoading(false);
      });
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  return (
    <div className="rounded-2xl border border-cream-200 bg-white p-4 space-y-3">
      <div className="flex items-center justify-between">
        <span className="text-[10px] font-semibold uppercase tracking-widest text-cream-500">
          Recommended for your machine
        </span>
        <button
          type="button"
          onClick={() => void load()}
          disabled={loading}
          className="rounded-md border border-cream-200 bg-white px-3 py-1 text-[11px] font-semibold text-cream-600 hover:text-terracotta disabled:opacity-60"
        >
          {loading ? "Detecting…" : "Re-detect"}
        </button>
      </div>

      {loading && !config && (
        <p className="text-[11px] text-cream-400">Detecting your hardware…</p>
      )}

      {error && <p className="text-[10px] text-coral-dark">{error}</p>}

      {config && (
        <>
          <p className="text-[12px] font-semibold text-cream-800">
            Tier: {config.tier}
          </p>
          <div className="grid grid-cols-2 gap-2 text-[11px] text-cream-700">
            <div>
              <span className="text-cream-400">Main coder</span>
              <br />
              <span className="font-mono">{config.mainCoder}</span>
            </div>
            <div>
              <span className="text-cream-400">Mini coder</span>
              <br />
              <span className="font-mono">{config.miniCoder}</span>
            </div>
            <div>
              <span className="text-cream-400">Censor</span>
              <br />
              <span className="font-mono">{config.censor}</span>
            </div>
            <div>
              <span className="text-cream-400">Oracle</span>
              <br />
              <span className="font-mono">{config.oracle}</span>
            </div>
          </div>
          <p className="text-[11px] leading-4 text-cream-500">
            {config.rationale}
          </p>
        </>
      )}
    </div>
  );
}
